#!/usr/bin/env python3
"""Generate INDEX.md from index/routes.json, index/sources.json and this repo's own entries.

The index is the map: goal -> route. Its hand-written parts are the two JSON files; the
local entries come from .claude-plugin/marketplace.json, so nothing here is edited twice.
Every route step must resolve, to a local entry or to a source in sources.json.

    python3 scripts/build-index.py          # write INDEX.md
    python3 scripts/build-index.py --check  # fail if INDEX.md is stale or a step dangles
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "INDEX.md"


def load(rel):
    return json.loads((ROOT / rel).read_text())


def main():
    check = "--check" in sys.argv[1:]
    local = {p["name"]: p for p in load(".claude-plugin/marketplace.json")["plugins"]}
    sources = {s["id"]: s for s in load("index/sources.json")["sources"]}
    routes = load("index/routes.json")["routes"]

    errors = []

    def step(ref):
        if "@" in ref:
            plugin, _, sid = ref.partition("@")
            src = sources.get(sid)
            if not src:
                errors.append(f"unknown source '{sid}' in step '{ref}'")
                return f"`{ref}`"
            link = f"[{src['name']}](https://github.com/{src['repo']})"
            return f"`{plugin}` from {link}" if plugin else link
        if ref not in local:
            errors.append(f"'{ref}' is not an entry in .claude-plugin/marketplace.json")
            return f"`{ref}`"
        p = local[ref]
        path = p["source"].removeprefix("./")
        return f"[`{ref}`]({path})"

    lines = [
        "# Index",
        "",
        "<!-- Generated by scripts/build-index.py from index/*.json and .claude-plugin/marketplace.json. Do not edit by hand. -->",
        "",
        "Goal first: find the route, then take it. Outside sources come before anything built here;",
        "this repo only keeps the combinations and hard-won routes nobody else has charted.",
        "",
        "**Legend:** ● charted only here (no outside source covers it) · *candidate* = vetted, not yet declared in nix-config.",
        "",
        "## Routes",
        "",
        "| Goal | Route | Note |",
        "|---|---|---|",
    ]
    for r in sorted(routes, key=lambda r: (not r.get("gap", False), r["goal"])):
        mark = "● " if r.get("gap") else ""
        route = " → ".join(step(s) for s in r["steps"])
        lines.append(f"| {mark}{r['goal']} | {route} | {r.get('note', '')} |")

    lines += [
        "",
        "## Sources",
        "",
        "| Source | Kind | How to use it | For | Status | Checked |",
        "|---|---|---|---|---|---|",
    ]
    for s in sources.values():
        status = "adopted" if s["adopted"] else "*candidate*"
        lines.append(
            f"| [{s['name']}](https://github.com/{s['repo']}) | {s['kind']} | {s['consume']} | {s['use_for']} | {status} | {s['checked']} |"
        )

    routed = {x for r in routes for x in r["steps"] if "@" not in x}
    unrouted = sorted(set(local) - routed)
    if unrouted:
        errors.append("no route reaches: " + ", ".join(unrouted))

    text = "\n".join(lines) + "\n"
    if errors:
        sys.exit("index: " + "\n       ".join(errors))
    if check:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit("index: INDEX.md is stale; run python3 scripts/build-index.py")
        print("index: up to date")
    else:
        OUT.write_text(text)
        print(f"index: wrote {OUT.relative_to(ROOT)} ({len(routes)} routes, {len(sources)} sources)")


if __name__ == "__main__":
    main()
